/**
 * BaZi Constants and Lookup Tables
 *
 * Reference tables for Five Elements relationships, Hidden Stems mappings,
 * and other essential BaZi calculation data.
 */

import type {
  HeavenlyStem,
  EarthlyBranch,
  WuXing,
  YinYang,
  HiddenStems,
} from "./types";

// ============ Stem to Element Mapping (天干五行) ============
export const STEM_ELEMENT: Record<HeavenlyStem, WuXing> = {
  甲: "木",
  乙: "木",
  丙: "火",
  丁: "火",
  戊: "土",
  己: "土",
  庚: "金",
  辛: "金",
  壬: "水",
  癸: "水",
};

// ============ Stem Yin-Yang (天干阴阳) ============
export const STEM_YIN_YANG: Record<HeavenlyStem, YinYang> = {
  甲: "阳",
  乙: "阴",
  丙: "阳",
  丁: "阴",
  戊: "阳",
  己: "阴",
  庚: "阳",
  辛: "阴",
  壬: "阳",
  癸: "阴",
};

// ============ Branch to Element Mapping (地支五行) ============
export const BRANCH_ELEMENT: Record<EarthlyBranch, WuXing> = {
  子: "水",
  丑: "土",
  寅: "木",
  卯: "木",
  辰: "土",
  巳: "火",
  午: "火",
  未: "土",
  申: "金",
  酉: "金",
  戌: "土",
  亥: "水",
};

// ============ Branch Yin-Yang (地支阴阳) ============
export const BRANCH_YIN_YANG: Record<EarthlyBranch, YinYang> = {
  子: "阳",
  丑: "阴",
  寅: "阳",
  卯: "阴",
  辰: "阳",
  巳: "阴",
  午: "阳",
  未: "阴",
  申: "阳",
  酉: "阴",
  戌: "阳",
  亥: "阴",
};

// ============ Hidden Stems in Branches (地支藏干) ============
// Based on traditional BaZi theory
export const BRANCH_HIDDEN_STEMS: Record<EarthlyBranch, HiddenStems> = {
  子: { main: "癸" },
  丑: { main: "己", sub: "癸", 余气: "辛" },
  寅: { main: "甲", sub: "丙", 余气: "戊" },
  卯: { main: "乙" },
  辰: { main: "戊", sub: "乙", 余气: "癸" },
  巳: { main: "丙", sub: "庚", 余气: "戊" },
  午: { main: "丁", sub: "己" },
  未: { main: "己", sub: "丁", 余气: "乙" },
  申: { main: "庚", sub: "壬", 余气: "戊" },
  酉: { main: "辛" },
  戌: { main: "戊", sub: "辛", 余气: "丁" },
  亥: { main: "壬", sub: "甲" },
};

// ============ Five Elements Relationships (五行生克) ============

// Generating cycle (相生): Wood→Fire→Earth→Metal→Water→Wood
export const WU_XING_GENERATES: Record<WuXing, WuXing> = {
  木: "火", // Wood generates Fire
  火: "土", // Fire generates Earth
  土: "金", // Earth generates Metal
  金: "水", // Metal generates Water
  水: "木", // Water generates Wood
};

// What generates this element
export const WU_XING_GENERATED_BY: Record<WuXing, WuXing> = {
  木: "水", // Wood is generated by Water
  火: "木", // Fire is generated by Wood
  土: "火", // Earth is generated by Fire
  金: "土", // Metal is generated by Earth
  水: "金", // Water is generated by Metal
};

// Controlling cycle (相克): Wood→Earth→Water→Fire→Metal→Wood
export const WU_XING_CONTROLS: Record<WuXing, WuXing> = {
  木: "土", // Wood controls Earth
  土: "水", // Earth controls Water
  水: "火", // Water controls Fire
  火: "金", // Fire controls Metal
  金: "木", // Metal controls Wood
};

// What controls this element
export const WU_XING_CONTROLLED_BY: Record<WuXing, WuXing> = {
  木: "金", // Wood is controlled by Metal
  土: "木", // Earth is controlled by Wood
  水: "土", // Water is controlled by Earth
  火: "水", // Fire is controlled by Water
  金: "火", // Metal is controlled by Fire
};

// ============ Month Branch (月支) to Season ============
export const MONTH_BRANCH_SEASON: Record<EarthlyBranch, WuXing> = {
  寅: "木",
  卯: "木",
  辰: "土", // Spring transition
  巳: "火",
  午: "火",
  未: "土", // Summer transition
  申: "金",
  酉: "金",
  戌: "土", // Autumn transition
  亥: "水",
  子: "水",
  丑: "土", // Winter transition
};

// ============ Hour Branch (时支) Mapping ============
// Maps hour (0-23) to Earthly Branch
export const HOUR_TO_BRANCH: Record<number, EarthlyBranch> = {
  23: "子",
  0: "子",
  1: "丑",
  2: "丑",
  3: "寅",
  4: "寅",
  5: "卯",
  6: "卯",
  7: "辰",
  8: "辰",
  9: "巳",
  10: "巳",
  11: "午",
  12: "午",
  13: "未",
  14: "未",
  15: "申",
  16: "申",
  17: "酉",
  18: "酉",
  19: "戌",
  20: "戌",
  21: "亥",
  22: "亥",
};

// Helper function to get hour branch
export function getHourBranch(hour: number): EarthlyBranch {
  const normalizedHour = hour === 23 ? 23 : hour % 24;
  return HOUR_TO_BRANCH[normalizedHour] as EarthlyBranch;
}

// ============ Day Stem to Hour Stem Table (日上起时法) ============
// Based on 甲己还甲, 乙庚起丙...
export const DAY_STEM_TO_HOUR_START: Record<HeavenlyStem, HeavenlyStem> = {
  甲: "甲", // 甲己日起甲子时
  己: "甲",
  乙: "丙", // 乙庚日起丙子时
  庚: "丙",
  丙: "戊", // 丙辛日起戊子时
  辛: "戊",
  丁: "庚", // 丁壬日起庚子时
  壬: "庚",
  戊: "壬", // 戊癸日起壬子时
  癸: "壬",
};

// ============ Pillar Position Weights (四柱权重) ============
// For day master strength calculation
export const PILLAR_WEIGHTS = {
  year: 0.1, // 10% influence
  month: 0.4, // 40% influence (月令最重)
  day: 0.3, // 30% influence (日支)
  hour: 0.2, // 20% influence
} as const;

// ============ Element Strength in Season (月令得令) ============
// Bonus for being in season
export const SEASON_ELEMENT_BONUS: Record<WuXing, WuXing[]> = {
  木: ["木"], // Wood strong in Wood season
  火: ["火"],
  土: ["土"],
  金: ["金"],
  水: ["水"],
};

// Penalty for being out of season (克制季节)
export const SEASON_ELEMENT_PENALTY: Record<WuXing, WuXing[]> = {
  木: ["金", "土"], // Wood weak when Metal or Earth is in season
  火: ["水", "金"],
  土: ["木", "水"],
  金: ["火", "木"],
  水: ["土", "火"],
};

// ============ Element Relationship Scores ============
export const ELEMENT_RELATIONSHIP_SCORES = {
  SAME: 10, // Same element (比肩/劫财)
  GENERATES: 8, // Element that generates me (正印/偏印)
  GENERATED_BY: -5, // Element I generate (食神/伤官) - drains
  CONTROLS: -8, // Element that controls me (正官/偏官)
  CONTROLLED_BY: -3, // Element I control (正财/偏财) - slight drain
} as const;

// ============ Stem Combination (天干合) ============
export const STEM_COMBINATIONS: [HeavenlyStem, HeavenlyStem, WuXing][] = [
  ["甲", "己", "土"], // 甲己合土
  ["乙", "庚", "金"], // 乙庚合金
  ["丙", "辛", "水"], // 丙辛合水
  ["丁", "壬", "木"], // 丁壬合木
  ["戊", "癸", "火"], // 戊癸合火
];

// ============ Branch Combinations (地支三合/六合) ============
// 三合局 (Three Harmony)
export const BRANCH_THREE_HARMONY: [
  EarthlyBranch,
  EarthlyBranch,
  EarthlyBranch,
  WuXing
][] = [
  ["申", "子", "辰", "水"], // 申子辰合水
  ["寅", "午", "戌", "火"], // 寅午戌合火
  ["巳", "酉", "丑", "金"], // 巳酉丑合金
  ["亥", "卯", "未", "木"], // 亥卯未合木
];

// 六合 (Six Harmony)
export const BRANCH_SIX_HARMONY: [EarthlyBranch, EarthlyBranch, WuXing][] = [
  ["子", "丑", "土"], // 子丑合土
  ["寅", "亥", "木"], // 寅亥合木
  ["卯", "戌", "火"], // 卯戌合火
  ["辰", "酉", "金"], // 辰酉合金
  ["巳", "申", "水"], // 巳申合水
  ["午", "未", "土"], // 午未合土
];

// ============ Branch Clashes (地支相冲) ============
export const BRANCH_CLASHES: [EarthlyBranch, EarthlyBranch][] = [
  ["子", "午"],
  ["丑", "未"],
  ["寅", "申"],
  ["卯", "酉"],
  ["辰", "戌"],
  ["巳", "亥"],
];

// ============ Branch Penalties (地支相刑) ============
export const BRANCH_PENALTIES: [
  EarthlyBranch,
  EarthlyBranch,
  string // Type of penalty
][] = [
  ["寅", "巳", "无恩之刑"],
  ["巳", "申", "无恩之刑"],
  ["申", "寅", "无恩之刑"],
  ["丑", "戌", "恃势之刑"],
  ["戌", "未", "恃势之刑"],
  ["未", "丑", "恃势之刑"],
  ["子", "卯", "无礼之刑"],
  ["卯", "子", "无礼之刑"],
  ["辰", "辰", "自刑"],
  ["午", "午", "自刑"],
  ["酉", "酉", "自刑"],
  ["亥", "亥", "自刑"],
];
