export enum Screen {
  HOME = 'HOME',
  BIRTH_CHART = 'BIRTH_CHART',
  REPORT = 'REPORT',
  TAROT_DAILY = 'TAROT_DAILY',
  TAROT_SPREAD = 'TAROT_SPREAD',
  SHOP_LIST = 'SHOP_LIST',
  PRODUCT_DETAIL = 'PRODUCT_DETAIL',
  EXPERTS = 'EXPERTS',
  BOOKING = 'BOOKING',
  INTAKE = 'INTAKE',
  DELIVERY = 'DELIVERY',
  USER_DASHBOARD = 'USER_DASHBOARD',
  ARCHIVES = 'ARCHIVES',
  ORDERS = 'ORDERS',
  ADMIN_PAYMENTS = 'ADMIN_PAYMENTS',
  ADMIN_CURRENCY = 'ADMIN_CURRENCY',
  ADMIN_SHIPPING = 'ADMIN_SHIPPING'
}

export interface NavProps {
  currentScreen: Screen;
  setScreen: (screen: Screen) => void;
}